version: "3.1"

services:
  main-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=lab_tool_db

    ports:
      - 5432:5432
    volumes:
      - ./docker_volumes:/data/postgresql/data

  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27017:27017
    volumes:
      - ./docker_volumes:/data/mongodb/data

  redis-db:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker_volumes:/data/redisdb/data
