version: "3.1"

services:
  main-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=lab_tool_db

    ports:
      - 5432:5432
    volumes:
      - ./docker_volumes:/data/postgresql/data
